### ISSUE TITLE
the header is not visible when scrolling in the list of signed-in users

### ISSUE THREAD

**Issue by jurakin** [sokolpezinok/orientacny-beh#4]
If there are too many users in the list of signed-in users, the header is not visible when scrolling. 

This should be easily fixed by setting `position: sticky` on the header.

**Comment by jurakin** [comment]
For unknown reasons, this method doesn't work and I can't think of anything else.

**Comment by xhyrom** [comment]
🤔

**Comment by jurakin** [comment]
Closing as fixed in v3.04 release.
