### ISSUE TITLE
Possible to change registration number

### ISSUE THREAD

**Issue by xkenia** [sokolpezinok/orientacny-beh#6]
In Profile is possible to change Registration number.

Also try to think about add club abbreviation ahead of this number (foreign runners should be from other club).

**Comment by jurakin** [comment]
On the profile tab, some values require the `MNG_BIG` permission to be editable. The registration number is one of them.

Have you used an account with this permission? If not, this is a bug.

**Comment by xkenia** [comment]
From web I'm not able to update this field, from app I'm able to do this.

**Comment by jurakin** [comment]
Can you please provide the user id and club you are signed in to, so I can reproduce the bug?

**Comment by xkenia** [comment]
OK, I make this loged as Spravce, I forget I have this right ;)
